apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: gcr.io/spiffe-io/spire-agent@sha256:e93e6879cc2a231a4983444312d8c32523c1106f388df275dca0db484cca312f
          imagePullPolicy: Always
          command: ["/bin/sleep", "1d"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /tmp/spire-agent/public
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /tmp/spire-agent/public
            type: Directory
